apiVersion: config.porch.kpt.dev/v1alpha1
kind: RootSyncSet
metadata:
  name: yuwen-test
  namespace: dev3
spec:
  clusterRefs:
  - apiVersion: container.cnrm.cloud.google.com/v1beta1
    kind: ContainerCluster
    name: us-central1
    namespace: dev3
  template:
    spec:
      sourceFormat: unstructured
      git:
        auth: none
        repo: http://github.com/yuwenma/kpt.git
        branch: dogfood-porch-installation
        dir: porch/ci/upstream/porch-install
