apiVersion: config.porch.kpt.dev/v1alpha1
kind: RemoteRootSyncSet
metadata:
  name: porch-install
  namespace: dev3
spec:
  clusterRefs:
  - apiVersion: container.cnrm.cloud.google.com/v1beta1
    kind: ContainerCluster
    name: us-east1
    namespace: dev3
  template:
    sourceFormat: unstructured
    oci:
      repository: gcr.io/yuwenma-gke-catalyst-goog-rlol/porch:v0.1
