apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
    config.kubernetes.io/parent-path: "google.com/gke-catalyst/yuwenma"
data:
  name: dev
