# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata: # kpt-merge: config-control/packagename
  name: packagename
  namespace: config-control
  annotations:
    internal.kpt.dev/upstream-identifier: 'resourcemanager.cnrm.cloud.google.com|Folder|config-control|packagename'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  displayName: packagename
  folderRef:
    name: environments
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata: # kpt-merge: config-control/packagename
  name: packagename
  namespace: config-control
  annotations:
    internal.kpt.dev/upstream-identifier: 'resourcemanager.cnrm.cloud.google.com|Project|config-control|packagename'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  name: packagename
  folderRef:
    name: environments
  billingAccountRef:
    #name: default
    # TODO: Is there a BillingAccount ref?
    external: 016C6E-5D5038-702920
  resourceID: googleprojectid
---
# We need to enable some services so we can enable other services
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: config-control/packagename-serviceusage
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    internal.kpt.dev/upstream-identifier: 'serviceusage.cnrm.cloud.google.com|Service|config-control|packagename-serviceusage'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
  name: packagename-serviceusage
  namespace: config-control
spec:
  resourceID: serviceusage.googleapis.com
  projectRef:
    name: packagename
